---
- name: Create temporary directory to store related files
  tempfile:
    state: directory
    suffix: seleniumhub
  register: seleniumhub_temp_dir

- name: Copy docker-compose to manager
  copy:
    src: docker-compose.yml
    dest: "{{ seleniumhub_temp_dir.path }}/docker-compose.yml"
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"

- name: Deploy Selenium HUB in Swarm
  command: 'docker stack deploy --compose-file {{ seleniumhub_temp_dir.path }}/docker-compose.yml seleniumhub'
  when: "inventory_hostname == groups['integr8-docker-swarm-manager'][0]"